/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;
import com.itextpdf.text.DocumentException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import ringkasankhusus.PatternRegex;
import ringkasankhusus.Notulen; 
import ringkasankhusus.IOFile;
import ringkasankhusus.CreatePDF;
import ringkasanumum.Klasifikasi;
import ringkasanumum.Praproses;
import ringkasanumum.RegexGenerator;
import static ringkasanumum.RingkasanUmum.agendaRapat;
import static ringkasanumum.RingkasanUmum.map;
import static ringkasanumum.RingkasanUmum.mapAgenda;
import static ringkasanumum.RingkasanUmum.sentences;
import ringkasanumum.SelectedSentences;
import ringkasanumum.TemplateGenerator;

/**
 *
 * @author mochamadtry
 */
public class GUIDesktop extends javax.swing.JFrame {

    /**
     * Creates new form GUIDesktop
     */
    public static int jenisRingkasan; 
    Notulen not = new Notulen();
    ringkasanumum.Notulen notulen  = new ringkasanumum.Notulen();
    public GUIDesktop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        MenuAwal = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        MainMenu = new javax.swing.JPanel();
        textFileName = new javax.swing.JTextField();
        proses = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        buttonFileName = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));
        setForeground(new java.awt.Color(204, 255, 255));

        jLayeredPane1.setLayout(new javax.swing.OverlayLayout(jLayeredPane1));

        MenuAwal.setBackground(new java.awt.Color(204, 204, 255));
        MenuAwal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel6.setText("PERINGKASAN RISALAH RAPAT");

        jLabel4.setIcon(new javax.swing.ImageIcon("G:\\Kuliah\\8th semester\\TA II\\tugas-akhir\\RingkasanKhusus\\logo kecil.png")); // NOI18N

        jButton1.setText("Mulai Peringkasan");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                klikButton(evt);
            }
        });

        javax.swing.GroupLayout MenuAwalLayout = new javax.swing.GroupLayout(MenuAwal);
        MenuAwal.setLayout(MenuAwalLayout);
        MenuAwalLayout.setHorizontalGroup(
            MenuAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuAwalLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuAwalLayout.createSequentialGroup()
                .addGap(0, 98, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuAwalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(188, 188, 188))
        );
        MenuAwalLayout.setVerticalGroup(
            MenuAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuAwalLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addGap(69, 69, 69))
        );

        jLayeredPane1.add(MenuAwal);

        MainMenu.setBackground(new java.awt.Color(204, 204, 255));
        MainMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        textFileName.setEditable(false);
        textFileName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFileNameActionPerformed(evt);
            }
        });

        proses.setText("Proses");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });

        jLabel3.setText("TUGAS AKHIR - 13513067");

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel1.setText("PERINGKASAN RISALAH RAPAT");

        jRadioButton2.setText("Ringkasan Umum");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Jenis Ringkasan");

        jRadioButton1.setText("Ringkasan Khusus");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonFileName.setText("Pilih File");
        buttonFileName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFileNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainMenuLayout = new javax.swing.GroupLayout(MainMenu);
        MainMenu.setLayout(MainMenuLayout);
        MainMenuLayout.setHorizontalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
            .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MainMenuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainMenuLayout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(MainMenuLayout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(jLabel2)
                            .addGap(52, 52, 52)
                            .addComponent(jRadioButton1)
                            .addGap(34, 34, 34)
                            .addComponent(jRadioButton2))
                        .addGroup(MainMenuLayout.createSequentialGroup()
                            .addComponent(textFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(buttonFileName)
                            .addGap(6, 6, 6)
                            .addComponent(proses))
                        .addGroup(MainMenuLayout.createSequentialGroup()
                            .addGap(176, 176, 176)
                            .addComponent(jLabel3)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        MainMenuLayout.setVerticalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
            .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MainMenuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(53, 53, 53)
                    .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainMenuLayout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(jLabel2))
                        .addComponent(jRadioButton1)
                        .addComponent(jRadioButton2))
                    .addGap(51, 51, 51)
                    .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainMenuLayout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(textFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(buttonFileName)
                        .addComponent(proses))
                    .addGap(58, 58, 58)
                    .addComponent(jLabel3)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLayeredPane1.add(MainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFileNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFileNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFileNameActionPerformed

    private void buttonFileNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFileNameActionPerformed
        final JFileChooser fileDialog = new JFileChooser();
        int returnVal = fileDialog.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String fileName = fileDialog.getSelectedFile().getPath();
            textFileName.setText(fileName);
            if (jenisRingkasan == 1){
                not.setPath(textFileName.getText());
                System.out.println(not.getPath());
            }
            else if (jenisRingkasan == 2){
                notulen.setPath(textFileName.getText());
                System.out.println("get file " + notulen.getPath());
            }
        }
    }//GEN-LAST:event_buttonFileNameActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        //        Notulen not  = new Notulen();
        //        //File f = new File(nameOfFile);
        if (jenisRingkasan == 1){
            
            PatternRegex pr = new PatternRegex();
            try {
                pr.fill(not);
            } catch (IOException ex) {
                Logger.getLogger(GUIDesktop.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                CreatePDF PDF = new CreatePDF(not);
            } catch (IOException | DocumentException ex) {
                Logger.getLogger(GUIDesktop.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if (jenisRingkasan == 2){
            //ringkasanumum.Notulen notulen  = new ringkasanumum.Notulen();
            RegexGenerator rg = new RegexGenerator();
            //File f = new File(textFileName.getText());
            Klasifikasi predict = new Klasifikasi();
            Praproses pp = new Praproses();
            ringkasanumum.IOFile file = new ringkasanumum.IOFile(); 
            SelectedSentences ss = new SelectedSentences();
            ringkasanumum.klasifikasiretorik.Klasifikasi klasifikasi = new ringkasanumum.klasifikasiretorik.Klasifikasi();
            ringkasanumum.klasifikasiretorik.FileUpload upload = new ringkasanumum.klasifikasiretorik.FileUpload(); 
            //TemplateGenerator template = new TemplateGenerator();
            //System.out.println("file " + f);
            try {
                System.out.println("file ");
                file.loadFile(notulen);
            } catch (IOException ex) {
                Logger.getLogger(GUIDesktop.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                upload.postFile(notulen);
            } catch (IOException | SQLException ex) {
                Logger.getLogger(GUIDesktop.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                klasifikasi.klasifikasi(notulen);
            } catch (Exception ex) {
                Logger.getLogger(GUIDesktop.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                predict.writeFile(notulen);
            } catch (IOException ex) {
                Logger.getLogger(GUIDesktop.class.getName()).log(Level.SEVERE, null, ex);
            }
            rg.regexTanggalRapat(notulen);
            rg.regexTahunSidang(notulen);
            rg.regexMasaPersidangan(notulen);
            rg.regexUrutanRapat(notulen);
            rg.regexDaftarHadirAnggota(notulen);
            
            try {
                agendaRapat = rg.regexAcara(notulen);
            } catch (IOException ex) {
                Logger.getLogger(GUIDesktop.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println("agenda Rapat: " + agendaRapat.size());
            map = rg.partSegmentasi(notulen);
            mapAgenda = rg.regexInterupsi(notulen);
            try {
                predict.prosesKlasifikasi(notulen);
            } catch (IOException ex) {
                Logger.getLogger(GUIDesktop.class.getName()).log(Level.SEVERE, null, ex);
            }
            //        ss.calcCosineSim(not);
            List<Integer> list = new ArrayList();
            ss.sentencesJoin(notulen);
//            ss.calcCosineSim(not);
            ss.calcCS(notulen);
//            ss.rankedSentencesCosine(notulen, 2);
            ss.rankedJavaILP(notulen, list);
//            ss.rankedSentencesMMR(notulen);
            
//            ss.rankedSentencesMMR(notulen);
            try {
                TemplateGenerator template = new TemplateGenerator(notulen);
            } catch (IOException | DocumentException ex) {
                Logger.getLogger(GUIDesktop.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println("print: " + notulen.getProsesAcara());
            System.out.println("print: " + notulen.getProsesInterupsi());
            System.out.println("print: " + notulen.getProsesPembicara());
            System.out.println("print: " + notulen.getProsesPembicara().get(1).equals("KETUA RAP AT"));
        }

    }//GEN-LAST:event_prosesActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        jenisRingkasan = 1; 
        System.out.println(jenisRingkasan);
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        
        jenisRingkasan = 2;
        System.out.println(jenisRingkasan);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void klikButton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_klikButton
        // TODO add your handling code here:
        MenuAwal.setVisible(false);
        MainMenu.setVisible(true);
    }//GEN-LAST:event_klikButton

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUIDesktop().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainMenu;
    private javax.swing.JPanel MenuAwal;
    private javax.swing.JButton buttonFileName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JButton proses;
    private javax.swing.JTextField textFileName;
    // End of variables declaration//GEN-END:variables
}
